<script type="text/x-magento-template" id="mysearch">


<li class="<%- data.row_class %> li-search" id="qs-option-<%- data.index %>" role="option">
                    <span class="qs-option-name li-name">
                       <p> <%- data.name %> </p> 
                       <p class="price"> <%- data.special_price %> </p>
                    </span> 
                    <span aria-hidden="true" class="li-image">
                        <img src="<%- data.image %>" alt="image of product"/> 
                    </span>
</li>
</script>